apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    appname: dogbreeds
  name: dogbreeds
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: dogbreeds
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        appname: dogbreeds
      name: dogbreeds
    spec:
      containers:
      - name: dogbreeds
        env: []
        image: dogbreeds4cba770a.azurecr.io/dogbreedsvc:1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5001
            scheme: HTTP
          initialDelaySeconds: 310
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5001
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 500m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    appname: dogbreeds
  name: dogbreeds
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    appname: dogbreeds
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dogbreeds-ingress
  namespace: dogbreeds-cb
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: dogbreeds
          servicePort: 80
        path: /dogbreeds/(.*)
